language: python
sudo: false
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database mailboxer;' -U postgres
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
script: 
  - "make travis_test"
